config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # external module
  devise_for :users, :controllers => { registrations: 'registrations' }

  # static pages
  get 'advice', to: 'home#advice'
  get 'my_runs', to: 'home#my_runs'

  # parnter
  get 'find_partner', to: 'home#find_partner'
  post 'fetch_partner', to: 'home#fetch_partner'

  #ranking
  get 'ranking', to: 'home#ranking'

  # spot
  get 'spots', to: 'home#spots'
  get 'like_run/:id', to: 'home#like_run', as: 'like_run'
  get 'unlike_run/:id', to: 'home#unlike_run', as: 'unlike_run'
  get 'define_run_as_spot/:id', to: 'home#define_run_as_spot', as: 'define_run_as_spot'
  # root 'home#landing'

  resources :invitations, only: [:create, :update]
  resources :friends

  # profil page
  get 'users/:id', to: 'users#show', as: 'user_show'
  # upload user picture
  post 'users/upload_pics', to: 'users#upload_pics', as: 'user_upload_picture'

  # graph page
  get 'dashboard', to: 'dashboard#index'
  # chat
  get 'messenger', to: 'messenger#index'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  resources :notifications, only: [:read] do
    post '/read', to: 'notifications#read', as: 'read_notification'
  end

  #friendships
  resources :friendships do
    member do
      post '/accept', to: 'friendships#accept', as: 'accept'
      post '/reject', to: 'friendships#reject', as: 'reject'
    end
  end

  resources :members, only: [:destroy]
  resources :dashboard
  resources :comments

  resources :member_requests do
    member do
      post "accept", to: "member_requests#accept", as: "accept"
      post "reject", to: "member_requests#reject", as: "reject"
    end
  end

  resources :posts do
    member do
      post 'like', to: 'posts#like'
      post 'dislike', to: 'posts#dislike'
      resources :comments
    end
  end
  # delete post rename
  delete 'posts/:id/delete', to: 'posts#destroy', as: 'delete_post'
  delete 'comments/:id/delete', to: 'comments#destroy', as: 'delete_comment'

  resources :events do
    member do
      put "like", to: "events#like"
      put "dislike", to: "events#dislike"
      post "leave", to: "events#leave", as: "leave"
    end
  end

  get "groups_filter", to: "groups#filter", as: "group_filter"
  get "events_filter", to: "events#filter", as: "event_filter"

  resources :groups do
    member do
      put "like", to: "groups#like"
      put "dislike", to: "groups#dislike"
      post "leave", to: "groups#leave", as: "leave"
    end
  end

  resources :configs

  resources :achievements do
    member do
      post 'success' => 'achievements#success'
      post 'failure' => 'achievements#failure'
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # post 'login' => 'sessions#create'
      # devise_for :users, only: [:sessions], path: '',
      #   path_names: {
      #     sign_in: 'login', sign_out: 'logout'
      #   }
      resources :home

      devise_scope :user do
        post 'sign_up' => 'registrations#create', :as => 'sign_up'
        post 'login' => 'sessions#create', :as => 'login'
        delete 'logout' => 'sessions#destroy', :as => 'logout'
      end
      # devise_for :users, only: [:sessions]
      resources :runs do
        member do
          get 'define_as_a_spot' => 'runs#define_as_a_spot', :as => 'define_as_a_spot'
          get 'like' => 'runs#like', :as => 'like'
          get 'unlike' => 'runs#unlike', :as => 'unlike'
        end
      end
      get 'get_spots' => 'runs#get_spots', :as => 'get_spots'

      resources :groups do
        member do
          get 'posts', to: 'groups#posts'
          put "like", to: "groups#like"
          put "dislike", to: "groups#dislike"
          post "leave", to: "groups#leave", as: "leave"
        end
      end

      resources :member_requests, only: [:create, :destroy] do
        member do
          post "accept", to: "member_requests#accept", as: "accept"
          post "reject", to: "member_requests#reject", as: "reject"
        end
      end

      resources :notifications, only: [:index]

      resources :events do
        member do
          get 'posts', to: 'events#posts'
          get 'like', to: 'events#like'
          get 'dislike', to: 'events#dislike'
        end
      end
      #friendships
      get '/friendships/notifications', to: 'friendships#notifications', as: 'notifications_friendship'
      resources :friendships do
        member do
          post '/accept', to: 'friendships#accept', as: 'accept'
          post '/reject', to: 'friendships#reject', as: 'reject'
        end
      end

      get '/stats', to: 'dashboard#stats'
      get '/ranking', to: 'ranking#index'

      resources :users do
        resources :upload_pics
      end
      resources :posts do
        member do
          post '/status', to: "posts#switch_private_status"
          post 'like', to: 'posts#like'
          post 'dislike', to: 'posts#dislike'
          post '/addpicture', to: "posts#add_picture_to_post"
        end
      end
      resources :comments

      resources :achievements do
        member do
          post 'success' => 'achievements#success'
          post 'failure' => 'achievements#failure'
        end
      end

      resources :conversations, only: [:index, :create] do
        resources :messages, only: [:index, :create]
      end
    end
  end

  # Documentation
  resources :apidocs, only: [:index]
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :notifications, as: :target, dependent: :destroy
  has_many :member_requests, as: :requests, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_one :config
  belongs_to :user
  accepts_nested_attributes_for :config
  validates :name, presence: true
  acts_as_votable

  has_attached_file :avatar, styles: { medium: "300x300>" }, default_url: "group_default.jpg"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def members
    self.member_requests.where(status: "accepted")
  end

  def pending_requests
    self.member_requests.where(status: "pending")
  end

  def find_member_request(user)
    self.member_requests.where(user_id: user).pluck(:id)
  end

  def is_member(user)
    self.member_requests.where(user_id: user.id, status: "accepted").pluck(:id).empty?
  end

  def get_picture
    if self.avatar.nil?
      "group-profil-default.jpg"
    else
      self.avatar.url
    end
  end


  # DOCUMENTATION
  include Swagger::Blocks

  swagger_schema :Group do
    key :required, [:id, :user_id]
    property :id do
      key :type, :integer
      key :format, :int64
    end
    property :name do
      key :type, :string
    end
    property :private do
      key :type, :boolean
    end
  end

  swagger_schema :GroupInput do
    allOf do
      schema do
        key :'$ref', :Group
      end
      schema do
        property :id do
          key :type, :integer
          key :format, :int64
        end
      end
    end
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < Api::V1::ApiController
  respond_to :json

  before_action :current_user, except: [:create]
  before_action :set_group, only: [:show, :edit, :posts, :update, :destroy, :like, :dislike, :leave]

  def index
    @groups = Group.all.order(created_at: :desc)
    json_groups = @groups.as_json
    json_groups.each_with_index do |group, i|
      if current_user.id == group['user_id']
        group['is_register'] = true
      else
        group['is_register'] = false
      end
      group['picture'] = @groups[i].avatar.url
    end
    render :json => { groups: json_groups, status: :ok }
  end

  def show
    @members = members_list
    @requests = requests_list
    render json: {
      group: @group,
      posts: @group.posts,
      members: @members,
      requests: @requests,
      status: :ok
    }
  end

  def posts
    posts = @group.posts
    tmp_posts = []
    posts.each do |post|
      tmp_comments = []
      tmp_post = post.attributes
      post.comments.each do |comment|
        tmp_comment = comment.attributes
        tmp_comment["user_fullname"] = comment.user.fullname
        tmp_comments << tmp_comment
      end
      tmp_post["comments"] = tmp_comments
      tmp_post["user"] = {
        user_id: post.user.id,
        full_name: post.user.fullname
      }
      tmp_posts << tmp_post
    end

    json_posts = tmp_posts.as_json
    json_posts.each_with_index do |post, i|
      if !posts[i].pictures.first.nil?
        post['picture'] = posts[i].pictures.first.url
      else
        post['picture'] = posts[i].picture
      end
      post['likes'] = posts[i].votes_for.size
      post['is_liked'] = current_user.voted_for?(posts[i])
    end
    render :json => { posts: json_posts, status: :ok }
  end


  def new
    @group = Group.new
  end

  def create
    if params != nil
      @group = Group.new(group_params(params))

      if @group != nil
        @group.save!

        render json: @group, status: 200
      else
        render json: @group.errors, status: 422
      end
    end
  end

  def edit
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @group.update(group_params(params))
      render json: @group, status: 200
    else
      render :json => @group.errors, :status => 422
    end
  end


  def destroy
    @group.destroy
    render json: {
      status: 200,
      message: 'Group deleted'
    }
  end

  def like
    @group.liked_by current_user
    render json: {
      status: 200
    }
  end

  def dislike
    @group.unliked_by current_user
    render json: {
      status: 200
    }
  end

  def leave
    if !@group.nil?
      if @group.try(:member_requests).find_by_user_id(current_user.id)
        if @group.destroy
          render json: {
            status: 200,
            message: 'You successfully left this group'
          }
        else
          render json: {
            status: 422,
            message: 'You canno\'t quit this group for the moment'
          }
        end
      else
        render json: {
          status: 422,
          message: 'You don\'t belong to this group'
        }
      end
    else
      render json: {
        status: 422,
        message: 'This group doesn\'t exist'
      }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find_by_id(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params(parameters)
    data = {}
    data[:user_id] = current_user.id
    data[:name] = parameters[:name] || "untitle"
    data[:description] = parameters[:description] || "Pas de description"
    data[:private_status] = parameters[:private_status] || false
    data
  end

  def members_list
    @data_members = []
    @group.members.each do |member|
      @data_members << {
        user: User.find(member.user_id).slice('id', 'firstname', 'lastname')
      }
    end
    @data_members
  end

  def requests_list
    @data_requests = []
    @group.pending_requests.each do |request|
      @data_requests << {
        user: User.find(request.user_id).slice('id', 'firstname', 'lastname')
      }
    end
    @data_requests
  end

  # DOCUMENTATION
  include Swagger::Blocks

  swagger_path '/api/v1/groups' do
    operation :post do
      key :description, 'Create a group'
      key :operationId, 'addGroup'
      key :produces, [
        'application/json'
      ]
      key :tags, [
        'group'
      ]
      parameter do
        key :name, :id
        key :name, :string
        key :private, :boolean
        key :user_id, :integer
        schema do
          key :'$ref', :GroupInput
        end
      end
      response 200 do
        key :description, 'Group created'
        schema do
          key :'$ref', :Group
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
  end
  swagger_path 'api/v1/groups/{id}' do
    operation :get do
      key :description, 'Get group information, profile'
      key :operationId, 'getGroup'
      key :tags, [
        'group'
      ]
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'Id of Group to fetch'
        key :required, true
        key :type, :integer
        key :format, :int64
      end
      response 200 do
        key :description, 'Group response'
        schema do
          key :'$ref', :Group
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
  end
  swagger_path 'api/v1/groups/{id}' do
    operation :put do
      key :description, 'Upload Group'
      key :operationId, 'uploadGroup'
      key :tags, [
        'group'
      ]
      key :produces, [
        'application/json'
      ]
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'Id of group to fetch'
        key :required, true
        key :type, :integer
        key :format, :int64
      end
      parameter do
        key :name, :string
        key :private, :boolean
      end
      response 200 do
        key :description, 'Group response'
        schema do
          key :'$ref', :Group
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
  end
  swagger_path 'api/v1/groups/{id}' do
    operation :delete do
      key :description, 'Delete group'
      key :operationId, 'deleteGroup'
      key :tags, [
        'group'
      ]
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'Id of group to fetch'
        key :required, true
        key :type, :integer
        key :format, :int64
      end
      response 200 do
        key :description, 'Group response'
        schema do
          key :'$ref', :Group
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :current_user
  before_action :set_group, only: [:show, :like, :dislike, :edit, :update, :destroy, :leave]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where.not(id: current_user.groups.ids + current_user.belongs_groups.pluck(:id))
    @group = Group.new
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @post = Post.new
    @posts = @group.posts
    @is_member = @group.try(:members).exists?(:user_id => current_user.id)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def like
    @group = Group.find(params[:id])
    @group.liked_by current_user
    redirect_to :back
  end

  def dislike
    @group = Group.find(params[:id])
    @group.unliked_by current_user
    redirect_to :back
  end

  # POST /groups
  # POST /groups.json
  def create
    group = Group.new(group_params)
    config = Config.new(params[:group][:config])

    respond_to do |format|
      if group.save
        config.group_id = group.id
        config.save
        format.html { redirect_to group, notice: 'Le groupe a été créé avec succès.' }
        format.json { render :show, status: :created, location: group }
      else
        format.html { render :new }
        format.json { render json: group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Le groupe a été mise à jour avec succès.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @success = @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url}
      format.js
    end
  end

  def leave
    respond_to do |format|
      if @group.member_requests.find_by_user_id(current_user.id).destroy
        @errors = false
        format.js
      else
        @errors = true
        format.js
      end
    end
  end

  def filter
    group_type = params[:type] == 2
    if !params[:type].blank?
      condition = ""
      if !params[:key_word].blank?
        condition += "lower(groups.name) LIKE ? "
        condition += "and " if params[:type].to_i != 2
      end
      condition += "groups.private_status is " + group_type if params[:type].to_i != 2
      print condition
      @groups = Group.where(condition, "%" + params[:key_word].downcase + "%")
    end
    print @groups.count
    respond_to do |format|
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:user_id, :name, :private_status, :description, :avatar, config_attributes: [ :is_invitable, :is_commentable])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(group, html: { multipart: true }) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label 'Nom du groupe' %>
    <%= f.text_field :name, { :class => 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.label 'Description' %>
    <%= f.text_area :description, { :class => 'form-control' } %>
  </div>
  <% if group.pictures.count > 0 %>
    <div class="img-responsive">
      <p>
        Image du groupe
      </p>
      <%= link_to group do %>
        <% image_tag group.pictures.first.url, class: "img-responsive", style: "height: 200px !important; margin-right: auto; margin-left: auto" %>
      <% end %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'Image' %>
    <%= f.file_field :avatar, { :class => 'form-control' } %>
  </div>
  <div class="check_box">
    <%= f.label 'Groupe privé ?' %>
    <%= f.check_box :private_status, { :class => 'form-control' } %>
  </div>

  <%= f.hidden_field :user_id, :value => @current_user.id %>
  <div class="form-submit">
    <%= f.submit 'Enregistrer', {:class => "btn btn-success" } %>
  </div>
<% end %>

app/views/groups/destroy.js.erb
<% if @success %>
  swal("", "Vous avez supprimé votre groupe", "success").then((value) => {
    location.reload();
  });
<% else %>
  swal("", 'Votre demande a échoué, veuillez réessayer ultérieurement.', "error").then((value) => {
    location.reload();
  });
<% end %>

app/views/groups/edit.html.erb
<%= render 'layouts/main_css' %>

<div class="page-head">
  <div class="page-title">
    <h1>Editer un groupe</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="portlet light portlet-fit bordered">
      <div class="portlet-body">
        <%= render 'form', group: @group %>

        <%= link_to 'Afficher', @group %> |
        <%= link_to 'Retour', groups_path %>
      </div>
    </div>
  </div>
</div>

app/views/groups/filter.js.erb
$('#suggest-groups').empty();

$('#suggest-groups').html("<%= escape_javascript (render 'groups/groups', :groups => @groups) %>");

app/views/groups/index.html.erb
<%= render 'layouts/main_css' %>
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-default" id="group-nav">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#group-nav-content" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="group-nav-content">
    <ul class="nav navbar-nav">
      <li>
        <a href="#my-groups" aria-controls="home" role="tab" data-toggle="tab">
          Mes groupes
        </a>
      </li>
      <li class="active">
        <a href="#others-groups" aria-controls="home" role="tab" data-toggle="tab">
          Découvrir
        </a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="new-group">
        <a data-toggle="modal" data-target="#new-group">
          <i class="glyphicon glyphicon-plus"></i> Créer un groupe
        </a>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<!-- BEGIN PAGE BASE CONTENT -->
<div class="search-page search-content-3">
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane" id="my-groups">
      <% current_user.all_groups.each do |group| %>
      <div class="col-md-4">
        <div class="col-md-12" style="background-color:white; padding:1em; margin-bottom : 10px;">
        <div class="tile-container">
          <div class="tile-thumbnail">
            <a href="javascript:;">
              <%= image_tag 'group_default.jpg', width: "100%", height: "auto" %>
            </a>
          </div>
          <div class="tile-title text-center">
            <h3>
              <%= link_to  group  do %>
              <%= truncate( group.name, length: 20) %>
              <% end %>
            </h3>
            <div style="margin-bottom: 2px">
              <%= group.private_status ? '<span class="label label-sm label-warning">PRIVEE</span>'.html_safe : '<span class="label label-sm label-success">PUBLIC</span>'.html_safe %></span>
            </div>
            <div style="margin-bottom: 2px">
              <span class="label label-sm label-info">Crée par : <%= group.user.fullname %></span>
            </div>
            <hr />
            <div class="tile-desc">
              <% if group.user == current_user %>
              <%= link_to group, :method => :delete, :remote => true  do %>
              <button class="btn btn-danger">Supprimer ce groupe</button>
              <% end %>
              <% else %>
              <%= link_to '<button class="btn btn-danger">Quitter ce groupe</button>'.html_safe, leave_group_path(:id => group.id), :method => :post, :remote => true %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane active" id="others-groups">
        <div class="col-lg-12" style="background-color:white; padding: 1em; margin-bottom: 10px;">
          <%= form_tag group_filter_path, method: :get, remote: true, class: "navbar-form navbar-left search-form" do %>
              <div class="search-filter bordered">
                <div class="input-icon right form-group">
                  <i class="icon-magnifier"></i>
                    <%= text_field_tag(
                        :key_word,
                        params[:key_word],
                        placeholder: "Nom du groupe",
                        class: "form-control"
                    ) %>
                </div>
                <%= select_tag(
                  :type,
                  options_for_select({"Public" => 0, "Privé" => 1, "Tout" => 2}, 2), class:"form-control", style: "display:none"
                ) %>
                <%= submit_tag "Filtrer", class: "btn btn-default" %>
              </div>
          <% end %>
        </div>
        <div class="col-lg-12" id="suggest-groups">
          <%= render "groups", groups: @groups %>
        </div>
    </div>
  </div>
</div>
  <!-- END PAGE BASE CONTENT -->

<!-- Modal -->
<div class="modal fade" id="new-group" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Nouveau groupe</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', group: @group %>
      </div>
    </div>
  </div>
</div>
<%#     <%= link_to '<i class="glyphicon glyphicon-align-justify"></i>'.html_safe, group
<%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_group_path(group)
<%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, group, method: :delete, data: { confirm: 'Are you sure?' }
<% if current_user.liked? group
<%= link_to "Unsubscribe", dislike_group_path(group), class: 'vote', method: :put
<% else
<%= link_to "Subscribe", like_group_path(group), class: 'vote', method: :put
<% end %>

app/views/groups/leave.js.erb
<% if !@error %>
  swal("", "Vous avez quitté ce groupe", "success").then((value) => {
    location.reload();
  });
<% else %>
  swal("", 'Votre demande a échoué, veuillez réessayer ultérieurement.', "error").then((value) => {
    location.reload();
  });
<% end %>

app/views/groups/new.html.erb
<%= render 'layouts/main_css' %>
<h1>Nouveau Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Retour', groups_path %>

app/views/groups/show.html.erb
<%= render 'layouts/main_css' %>
  <button style="margin-bottom: 10px;" class="btn btn-success">   <%= link_to groups_path do %> Retour <% end %> </button>

<%= image_tag(@group.avatar.url, :alt => "profil", :class => "img-responsive") %>
<div class="innerwrap" style="width:100%; border-top: 2px solid #e9ecf3;">
  <section class="section1 clearfix">
    <div>
      <div class="row grid clearfix">
        <div class="col-md-10 first">
          <h1><%= @group.name %></h1>
          <div>
            <%= @group.description %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="row">
            <div class="col-md-12 social-stats-section">
              <h1>
                <i class="fa fa-user-o"> </i>
                <%= @group.members.size %>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if @group.user == current_user %>
      <div class="text-right margin-bottom-10" style="padding: 5px;">
        <%= link_to edit_group_path(@group) do %>
          <button class="btn blue"><i class="icon-settings"></i> Modifier les informations du groupe</button>
        <% end %>
      </div>
    <% end %>
  </section>
  <section class="section2 clearfix">
    <% if !@group.is_member(current_user) or @group.user == current_user %>
      <div class="row">
        <div class="col-md-8">
            <div class="portlet light portlet-fit bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-clock-o font-green" aria-hidden="true" style="font-size: 20px;"></i>
                        <span class="caption-subject bold font-green uppercase">Fil d'actualité</span>
                        <span class="caption-helper">Votre fil d'actualité</span>
                    </div>
                    <div class="clearfix"></div>
                    <div class="container-index">
                      <div class="col-md-12 main-input-container">
                        <%= render 'posts/form', post: @post, group: @group, event: nil %>
                      </div>
                    </div>
                </div>
                <!-- all posts -->
                <%= render 'posts/display_all', posts: @posts %>
            </div>
        </div>
        <div class="col-md-4">
          <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
              <div class="clearfix"></div>
              <div class="col-md-12">
                <!-- Button trigger modal -->
                <!--<button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#myModal">
                  Paramètres
                </button>-->

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Paramètres</h4>
                      </div>
                      <div class="modal-body">
                        <%= render 'configs/form', config: @group.try(:config) ? @group.config : Config.new, group: @group %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <%= render 'member_requests/form', request: @group, type: "group", member_request: MemberRequest.new %>
              </div>
              <div class="col-md-12" style="max-height:200px; overflow-y:scroll;">
                <h4>Notifications</h4>
                <hr />
                <% if @group.user == current_user %>
                  <% @group.pending_requests.each do |request| %>
                  <div class="alert alert-info">
                    <%= User.find(request.user_id).try(:fullname) %> aimerait rejoindre votre groupe.
                    <%= link_to accept_member_request_path(:id => request.id), :method => :post, :remote => true do %><i class="fa fa-check"></i><% end %>
                    <%= link_to reject_member_request_path(:id => request.id), :method => :post, :remote => true do %><i class="fa fa-close"></i><% end %>
                  </div>
                  <% end %>
                <% end %>
              </div>
              <hr />
              <div class="col-md-12">
                <h4>Membres</h4>
                <hr />
                <div class="group-member">
                  <span class="label label-success">PROPRIETAIRE</span>
                  <%= @group.user.fullname %>
                </div>
                <% @group.members.each do |member| %>
                <div class="group-member">
                  <span class="label label-info">Membre</span>
                  <%= User.find(member.user_id).fullname %>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <% end %>