config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # external module
  devise_for :users, :controllers => { registrations: 'registrations' }

  # static pages
  get 'advice', to: 'home#advice'
  get 'my_runs', to: 'home#my_runs'

  # parnter
  get 'find_partner', to: 'home#find_partner'
  post 'fetch_partner', to: 'home#fetch_partner'

  #ranking
  get 'ranking', to: 'home#ranking'

  # spot
  get 'spots', to: 'home#spots'
  get 'like_run/:id', to: 'home#like_run', as: 'like_run'
  get 'unlike_run/:id', to: 'home#unlike_run', as: 'unlike_run'
  get 'define_run_as_spot/:id', to: 'home#define_run_as_spot', as: 'define_run_as_spot'
  # root 'home#landing'

  resources :invitations, only: [:create, :update]
  resources :friends

  # profil page
  get 'users/:id', to: 'users#show', as: 'user_show'
  # upload user picture
  post 'users/upload_pics', to: 'users#upload_pics', as: 'user_upload_picture'

  # graph page
  get 'dashboard', to: 'dashboard#index'
  # chat
  get 'messenger', to: 'messenger#index'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end

  resources :notifications, only: [:read] do
    post '/read', to: 'notifications#read', as: 'read_notification'
  end

  #friendships
  resources :friendships do
    member do
      post '/accept', to: 'friendships#accept', as: 'accept'
      post '/reject', to: 'friendships#reject', as: 'reject'
    end
  end

  resources :members, only: [:destroy]
  resources :dashboard
  resources :comments

  resources :member_requests do
    member do
      post "accept", to: "member_requests#accept", as: "accept"
      post "reject", to: "member_requests#reject", as: "reject"
    end
  end

  resources :posts do
    member do
      post 'like', to: 'posts#like'
      post 'dislike', to: 'posts#dislike'
      resources :comments
    end
  end
  # delete post rename
  delete 'posts/:id/delete', to: 'posts#destroy', as: 'delete_post'
  delete 'comments/:id/delete', to: 'comments#destroy', as: 'delete_comment'

  resources :events do
    member do
      put "like", to: "events#like"
      put "dislike", to: "events#dislike"
      post "leave", to: "events#leave", as: "leave"
    end
  end

  get "groups_filter", to: "groups#filter", as: "group_filter"
  get "events_filter", to: "events#filter", as: "event_filter"

  resources :groups do
    member do
      put "like", to: "groups#like"
      put "dislike", to: "groups#dislike"
      post "leave", to: "groups#leave", as: "leave"
    end
  end

  resources :configs

  resources :achievements do
    member do
      post 'success' => 'achievements#success'
      post 'failure' => 'achievements#failure'
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # post 'login' => 'sessions#create'
      # devise_for :users, only: [:sessions], path: '',
      #   path_names: {
      #     sign_in: 'login', sign_out: 'logout'
      #   }
      resources :home

      devise_scope :user do
        post 'sign_up' => 'registrations#create', :as => 'sign_up'
        post 'login' => 'sessions#create', :as => 'login'
        delete 'logout' => 'sessions#destroy', :as => 'logout'
      end
      # devise_for :users, only: [:sessions]
      resources :runs do
        member do
          get 'define_as_a_spot' => 'runs#define_as_a_spot', :as => 'define_as_a_spot'
          get 'like' => 'runs#like', :as => 'like'
          get 'unlike' => 'runs#unlike', :as => 'unlike'
        end
      end
      get 'get_spots' => 'runs#get_spots', :as => 'get_spots'

      resources :groups do
        member do
          get 'posts', to: 'groups#posts'
          put "like", to: "groups#like"
          put "dislike", to: "groups#dislike"
          post "leave", to: "groups#leave", as: "leave"
        end
      end

      resources :member_requests, only: [:create, :destroy] do
        member do
          post "accept", to: "member_requests#accept", as: "accept"
          post "reject", to: "member_requests#reject", as: "reject"
        end
      end

      resources :notifications, only: [:index]

      resources :events do
        member do
          get 'posts', to: 'events#posts'
          get 'like', to: 'events#like'
          get 'dislike', to: 'events#dislike'
        end
      end
      #friendships
      get '/friendships/notifications', to: 'friendships#notifications', as: 'notifications_friendship'
      resources :friendships do
        member do
          post '/accept', to: 'friendships#accept', as: 'accept'
          post '/reject', to: 'friendships#reject', as: 'reject'
        end
      end

      get '/stats', to: 'dashboard#stats'
      get '/ranking', to: 'ranking#index'

      resources :users do
        resources :upload_pics
      end
      resources :posts do
        member do
          post '/status', to: "posts#switch_private_status"
          post 'like', to: 'posts#like'
          post 'dislike', to: 'posts#dislike'
          post '/addpicture', to: "posts#add_picture_to_post"
        end
      end
      resources :comments

      resources :achievements do
        member do
          post 'success' => 'achievements#success'
          post 'failure' => 'achievements#failure'
        end
      end

      resources :conversations, only: [:index, :create] do
        resources :messages, only: [:index, :create]
      end
    end
  end

  # Documentation
  resources :apidocs, only: [:index]
end

app/controllers/api/v1/home_controller.rb
class Api::V1::HomeController < Api::V1::ApiController
  respond_to :json

  # before_action :current_user, except: [:create]
  before_action :authenticate_user!, :current_user

  def index
    @posts = Post.all.order(created_at: :desc)
    tmp_posts = []
    @posts.each do |post|
      tmp_comments = []
      tmp_post = post.attributes
      post.comments.each do |comment|
        tmp_comment = comment.attributes
        tmp_comment["user_fullname"] = comment.user.fullname
        tmp_comments << tmp_comment
      end
      tmp_post["comments"] = tmp_comments
      tmp_post["user"] = {
        user_id: post.user.id,
        full_name: post.user.fullname
      }
      tmp_posts << tmp_post
    end

    json_posts = tmp_posts.as_json
    json_posts.each_with_index do |post, i|
      if !@posts[i].pictures.first.nil?
        post['picture'] = @posts[i].pictures.first.url
      else
        post['picture'] = @posts[i].picture
      end
      post['likes'] = @posts[i].votes_for.size
      post['is_liked'] = current_user.voted_for?(@posts[i])
    end
    render :json => { posts: json_posts, status: :ok }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index]
  before_action :current_user, only: [:my_runs]

  def index
    @posts = Post.order(created_at: 'DESC').limit(5)
    @post = Post.new
    @run = current_user.runs.last
    @events = Event.limit 5
    @groups = Group.limit 5
  end

  def advice
  end

  def my_runs
    @last_run = current_user.runs.last
    @runs = Run.where(user_id: @current_user.id).order(created_at: 'DESC')
  end

  def spots
    @runs = Run.where(is_spot: true).order(created_at: 'DESC')
    @last_run = @runs.first
  end

  def define_run_as_spot
    @run = Run.find(params[:id])
    if @run.update(is_spot: !@run.is_spot)
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def like_run
    @run = Run.find(params[:id])
    @run.liked_by current_user
    redirect_to spots_path
  end

  def unlike_run
    @run = Run.find(params[:id])
    @run.unliked_by current_user
    redirect_to spots_path
  end

  def landing
    if current_user
      print 'Should redirect to index'
    end
  end

  def find_partner
  end

  def fetch_partner
    args = partner_params

    if args[:level].to_i == 0
      users = User.where("id != ?", current_user.id)
                  .near(args[:city], args[:range].to_i, unit: :km)
    elsif args[:level].to_i <= 12
      users = User.where("average_speed < ? AND id != ?", args[:level], current_user.id)
                  .near(args[:city], args[:range].to_i, unit: :km)
    else
      users = User.where("average_speed > ? AND id != ?", args[:level], current_user.id)
                  .near(args[:city], args[:range].to_i, unit: :km)
    end

    geo_tab = []
    geo_tab << Geocoder.coordinates(args[:city])

    avatars = users.map {|x| x.avatar.url }
    u = users.as_json
    u.each_with_index do |x, index|
      x[:avatar] = avatars[index]
      puts [x['latitude'].to_f, x['longitude'].to_f]
      geo_tab << [x['latitude'].to_f, x['longitude'].to_f] if !x['latitude'].nil?
    end

    puts geo_tab.inspect
    puts geo_tab

    center = Geocoder::Calculations.geographic_center(geo_tab)

    render json: {
      users: u,
      center: center,
      zoom: 12.5 - (args[:range].to_f / 10.0)
    }
  end

  def ranking
    @filter = params[:filter] || 'speed'
    if @filter == 'calorie'
      @users = User.order(total_calorie: :desc)
    elsif @filter == 'kilometer'
      @users = User.order(kilometer_done: :desc)
    else
      @users = User.order(average_speed: :desc)
    end

    @users
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def partner_params
    params.require(:partner).permit(:city, :range, :level)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/landing.html.erb
<div class="parent">
    <div class="child text-center">
      <h1 class="true-lies landing-title">RunIT</h1>
      <h2 class="landing-subtitle">BETTER KEEP RUNNING</h2>
      <div class="landing-menu">
        <h2>
          <a href="/users/sign_in">Login</a>
        </h2>
      </div>
    </div>
</div>

<%# content_for :javascript do %>
  <!-- <script type='text/javascript'>
    var i = 1;
    var img_bg = ["<%= asset_path('landing1.jpg') %>",
               "<%= asset_path('landing2.jpg') %>",
               "<%= asset_path('landing3.jpg') %>",
               "<%= asset_path('landing4.jpg') %>",
               "<%= asset_path('landing5.jpg') %>"];
  </script> -->
<%# end %>

app/views/home/ranking.html.erb
<%= render 'layouts/main_css' %>

<!-- BEGIN PAGE HEAD-->
<div class="page-head">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
        <h1>Classement
        </h1>
    </div>
    <!-- END PAGE TITLE -->
</div>
<!-- END PAGE HEAD-->

<div class="row">
  <div class="col-md-12">
    <div class="portlet light portlet-fit bordered">
      <div class="portlet-title">
          <div class="caption">
              <i class="fa fa-area-chart font-green" style="font-size: 20px;"></i>
              <span class="caption-subject bold font-green uppercase">
                <% if @filter == 'calorie' %>
                  Caloris brûler
                <% elsif @filter == 'kilometer' %>
                  Kilomètres parcourus
                <% else %>
                  Vitesse moyenne
                <% end %>
              </span>
          </div>
      </div>
      <div class="portlet-body">
        <div class="margin-bottom-15">
          <p>Filtre :</p>
          <% if @filter == 'calorie' %>
            <a href="/ranking?filter=speed"><button class="btn green btn-outline">Vitesse moyenne</button></a>
            <button class="btn green">Calorie brûler</button>
            <a href="/ranking?filter=kilometer"><button class="btn green btn-outline">Kilomètres parcourus</button></a>
          <% elsif @filter == 'kilometer' %>
            <a href="/ranking?filter=speed"><button class="btn green btn-outline">Vitesse moyenne</button></a>
            <a href="/ranking?filter=calorie"><button class="btn green btn-outline">Calorie brûler</button></a>
            <button class="btn green">Kilomètres parcourus</button>
          <% else %>
            <button class="btn green">Vitesse moyenne</button>
            <a href="/ranking?filter=calorie"><button class="btn green btn-outline">Calorie brûler</button></a>
            <a href="/ranking?filter=kilometer"><button class="btn green btn-outline">Kilomètres parcourus</button></a>
          <% end %>
        </div>
        <table class="table table-bordered table-striped table-condensed flip-content">
            <thead class="flip-content">
              <tr>
                <th>Nom</th>
                <th>Vitesse moyenne</th>
                <th>Calorie brûler</th>
                <th>Kilomètres parcourus</th>
                <th>Actions</th>
              </tr>
            </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.fullname %></td>
                <td><%= user.average_speed %></td>
                <td><%= user.total_calorie %></td>
                <td><%= user.kilometer_done %></td>
                <td><a href="/users/<%= user.id %>">Voir le profil</a></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/home/shared_runs.html.erb
<%= render 'layouts/main_css' %>

<% content_for :javascript_head do %>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js'></script>
  <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.js'></script>
<% end %>

<!-- BEGIN PAGE HEAD-->
<div class="page-head">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
        <h1>Les courses partagés
        </h1>
    </div>
    <!-- END PAGE TITLE -->
</div>
<!-- END PAGE HEAD-->
<!-- BEGIN DASHBOARD STATS 1-->
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 blue" href="#">
            <div class="visual">
                <i class="fa fa-calendar"></i>
            </div>
            <div class="details">
                <div class="number" style="font-size: 24px">
                    <span id="run-date" data-counter="counterup" data-value="1349"><%= @last_run.started_at.strftime("%Y-%m-%d") if @last_run %></span>
                </div>
                <div class="desc"> Date </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 red" href="#">
            <div class="visual">
                <i class="fa fa-clock-o"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="run-total-time" data-counter="counterup" data-value="12,5"><%= @last_run.total_time if @last_run %></span></div>
                <div class="desc"> Temps total </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 green" href="#">
            <div class="visual">
                <i class="fa fa-tachometer"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="run-max-speed" data-counter="counterup" data-value="549"><%= @last_run.max_speed if @last_run %></span>
                </div>
                <div class="desc"> Vitesse Max </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 purple" href="#">
            <div class="visual">
                <i class="fa fa-map"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="run-total-distance" data-counter="counterup" data-value="89"><%= @last_run.total_distance if @last_run %></span></div>
                <div class="desc"> Distance </div>
            </div>
        </a>
    </div>
</div>

<div class="row">
  <div class="col-md-12">
        <div class="map-container">
          <div class="run-info">
          </div>
          <div id='map'></div>
          <div id='data-run' data-run="<%= @last_run.to_json %>"></div>
        </div>
      </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="portlet box green">
      <div class="portlet-title">
        <div class="caption">
          <i class="icon-graph"></i>
           Les courses
        </div>
      </div>
      <div class="portlet-body flip-scroll">
        <table class="table table-bordered table-striped table-condensed flip-content">
            <thead class="flip-content">
              <tr>
                <th>Utilisateur</th>
                <th>Like</th>
                <th>Date</th>
                <th>Vitesse max</th>
                <th>Distance</th>
                <th>Temps total</th>
                <th>Action</th>
              </tr>
            </thead>

          <tbody>
            <% @runs.each do |run| %>
              <tr>
                <td><%= run.user.fullname %></td>
                <td><%= run.votes_for.size %></td>
                <td><%= run.started_at.to_formatted_s(:short) %></td>
                <td><%= run.max_speed %> km/h</td>
                <td><%= run.total_distance %> m</td>
                <td><%= run.total_time %> min</td>
                <td>
                  <a href="#" class="show-run" data-run="<%= run.to_json %>">
                    <button class="btn green">Afficher</button>
                  </a>
                  <% if current_user.voted_for? run %>
                    <%= link_to unlike_run_path(id: run.id) do %><button class="btn btn-outline red btn-sm" type="button">Je n'aime plus</button><%end %>
                  <% else %>
                    <%= link_to like_run_path(id: run.id) do %><button class="btn btn-outline green btn-sm" type="button">J'aime</button><%end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>
  <script>
    mapboxgl.accessToken = 'pk.eyJ1Ijoiam9ucXVhY2giLCJhIjoiY2l5eDY5b29hMDA0NjJ3bGV4bzFrMW44OSJ9.D_SMbkoqc7wofC7cEVL8jA';

    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/jonquach/ciz96k5qw004s2so5j7fje47d'
    });

    $('.show-run').click(function(e) {
      e.preventDefault();
      console.log($(this).attr('data-run'));
      makeLayer($(this).attr('data-run'));
      return false;
    })

    var oldLayer = "";

    var makeLayer = function(obj) {
      try {
        var run = JSON.parse(obj);

        if (run == null) {
          console.log(run, obj);
          console.log('There is no run to display');
          return;
        }

        var coordinates = [];
        var rc = JSON.parse(run.coordinates);
      } catch(e) {
        console.error('Run is not parsable ->', e);
        return;
      }

      for (var i = 0; i < rc.length; ++i) {
        coordinates.push([rc[i].longitude, rc[i].latitude])
      }

      console.log(run, coordinates);

      console.log(new Date(run.started_at));
      $("#run-date").html(createDate(run.started_at));
      $("#run-total-time").html(run.total_time);
      $("#run-max-speed").html(run.max_speed);
      $("#run-total-distance").html(run.total_distance);

      var layer = {
        "id": "route" + run.id,
        "type": "line",
        "source": {
            "type": "geojson",
            "data": {
                "type": "Feature",
                "properties": {},
                "geometry": {
                    "type": "LineString",
                    "coordinates": coordinates
                }
            }
        },
        "layout": {
            "line-join": "round",
            "line-cap": "round"
        },
        "paint": {
            "line-color": "#17eec3",
            "line-opacity": 0.65,
            "line-width": 6,
            "line-blur": 2
        }
      }

      if (oldLayer != "") {
        console.log('remove old layer', oldLayer);
        map.removeLayer(oldLayer);
        map.removeSource(oldLayer);
      }

      // Fly to location, centering the map on the average point, by total
      var avr_pt = Math.round(coordinates.length / 2);
      map.flyTo({
          center: [coordinates[avr_pt][0], coordinates[avr_pt][1]]
      });

      oldLayer = 'route' + run.id;
      map.addLayer(layer);
    }

    map.addControl(new mapboxgl.NavigationControl());
    map.addControl(new mapboxgl.GeolocateControl());
    map.addControl(new MapboxGeocoder({
      accessToken: mapboxgl.accessToken
    }));
    map.on('result', function(ev) {
        map.getSource('single-point').setData(ev.result.geometry);
    });

    map.on('load', function () {
       makeLayer($('#data-run').attr('data-run'));
    });

    function createDate(str) {
      date = new Date(str);
      day = date.getDay() + 1;
      if (day < 10) {
        day = '0' + day;
      }
      month = date.getMonth() + 1;
      if (month < 10) {
        month = '0' + month;
      }
      year = date.getFullYear();
      total = year + '-' + month + '-' + day;
      return total;
    }
  </script>
<% end %>

<% content_for :stylesheet do %>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css' rel='stylesheet' />
  <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.css' type='text/css' />
<% end %>

app/views/home/spots.html.erb
<%= render 'layouts/main_css' %>

<% content_for :javascript_head do %>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js'></script>
  <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.js'></script>
<% end %>

<!-- BEGIN PAGE HEAD-->
<div class="page-head">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
        <h1>Les courses partagées
        </h1>
    </div>
    <!-- END PAGE TITLE -->
</div>
<!-- END PAGE HEAD-->
<!-- BEGIN DASHBOARD STATS 1-->
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 blue" href="#">
            <div class="visual">
                <i class="fa fa-calendar"></i>
            </div>
            <div class="details">
                <div class="number" style="font-size: 24px">
                    <span id="run-date" data-counter="counterup" data-value="1349"><%= @last_run.started_at.strftime("%Y-%m-%d") if @last_run %></span>
                </div>
                <div class="desc"> Date </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 red" href="#">
            <div class="visual">
                <i class="fa fa-clock-o"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="run-total-time" data-counter="counterup" data-value="12,5"><%= @last_run.total_time if @last_run %></span></div>
                <div class="desc"> Temps total </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 purple" href="#">
            <div class="visual">
                <i class="fa fa-map"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="run-total-distance" data-counter="counterup" data-value="89"><%= @last_run.total_distance if @last_run %></span></div>
                <div class="desc"> Distance </div>
            </div>
        </a>
    </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a class="dashboard-stat dashboard-stat-v2 green" href="#">
            <div class="visual">
                <i class="fa fa-heart-o"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="run-like" data-counter="counterup" data-value="549"><%= @last_run.votes_for.size if @last_run %></span>
                </div>
                <div class="desc"> J'aime </div>
            </div>
        </a>
    </div>
</div>

<div class="row">
  <div class="col-md-12">
        <div class="map-container">
          <div class="run-info">
          </div>
          <div id='map'></div>
          <div id='data-run' data-run="<%= @last_run.to_json %>"></div>
        </div>
      </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="portlet box green">
      <div class="portlet-title">
        <div class="caption">
          <i class="icon-graph"></i>
           Les courses partagées
        </div>
      </div>
      <div class="portlet-body flip-scroll">
        <p>En cliquant sur "Afficher", la course va s'afficher sur la carte</p>
        <table class="table table-bordered table-striped table-condensed flip-content">
            <thead class="flip-content">
              <tr>
                <th>Coureur</th>
                <th>Like</th>
                <th>Date</th>
                <th>Distance</th>
                <th>Temps total</th>
                <th>Action</th>
              </tr>
            </thead>

          <tbody>
            <% @runs.each do |run| %>
              <tr>
                <td><%= run.user.fullname %></td>
                <td><%= run.votes_for.size %></td>
                <td><%= run.started_at.to_formatted_s(:short) %></td>
                <td><%= run.total_distance %> m</td>
                <td><%= run.total_time %> min</td>
                <td>
                  <a href="#" class="show-run" data-run="<%= run.to_json %>">
                    <button class="btn green">Afficher</button>
                  </a>
                  <% if current_user.voted_for? run %>
                    <%= link_to unlike_run_path(run.id) do %><button class="btn btn-outline red btn-sm" type="button">Je n'aime plus</button> <%end %>
                  <% else %>
                    <%= link_to like_run_path(run.id) do %><button class="btn btn-outline green btn-sm" type="button">J'aime</button> <%end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>
  <script>
    mapboxgl.accessToken = 'pk.eyJ1Ijoiam9ucXVhY2giLCJhIjoiY2l5eDY5b29hMDA0NjJ3bGV4bzFrMW44OSJ9.D_SMbkoqc7wofC7cEVL8jA';

    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/jonquach/ciz96k5qw004s2so5j7fje47d'
    });

    $('.show-run').click(function(e) {
      e.preventDefault();
      console.log($(this).attr('data-run'));
      makeLayer($(this).attr('data-run'));
      return false;
    })

    var oldLayer = "";

    var makeLayer = function(obj) {
      try {
        var run = JSON.parse(obj);

        if (run == null) {
          console.log(run, obj);
          console.log('There is no run to display');
          return;
        }

        var coordinates = [];
        var rc = JSON.parse(run.coordinates);
      } catch(e) {
        console.error('Run is not parsable ->', e);
        return;
      }

      for (var i = 0; i < rc.length; ++i) {
        coordinates.push([rc[i].longitude, rc[i].latitude])
      }

      console.log(run, coordinates);

      console.log(new Date(run.started_at));
      $("#run-date").html(createDate(run.started_at));
      $("#run-total-time").html(run.total_time);
      // $("#run-like").html(run.likes);
      $("#run-total-distance").html(run.total_distance);

      var layer = {
        "id": "route" + run.id,
        "type": "line",
        "source": {
            "type": "geojson",
            "data": {
                "type": "Feature",
                "properties": {},
                "geometry": {
                    "type": "LineString",
                    "coordinates": coordinates
                }
            }
        },
        "layout": {
            "line-join": "round",
            "line-cap": "round"
        },
        "paint": {
            "line-color": "#17eec3",
            "line-opacity": 0.65,
            "line-width": 6,
            "line-blur": 2
        }
      }

      if (oldLayer != "") {
        console.log('remove old layer', oldLayer);
        map.removeLayer(oldLayer);
        map.removeSource(oldLayer);
      }

      // Fly to location, centering the map on the average point, by total
      var avr_pt = Math.round(coordinates.length / 2);
      map.flyTo({
          center: [coordinates[avr_pt][0], coordinates[avr_pt][1]]
      });

      oldLayer = 'route' + run.id;
      map.addLayer(layer);
    }

    map.addControl(new mapboxgl.NavigationControl());
    map.addControl(new mapboxgl.GeolocateControl());
    map.addControl(new MapboxGeocoder({
      accessToken: mapboxgl.accessToken
    }));
    map.on('result', function(ev) {
        map.getSource('single-point').setData(ev.result.geometry);
    });

    map.on('load', function () {
       makeLayer($('#data-run').attr('data-run'));
    });

    function createDate(str) {
      date = new Date(str);
      day = date.getDay() + 1;
      if (day < 10) {
        day = '0' + day;
      }
      month = date.getMonth() + 1;
      if (month < 10) {
        month = '0' + month;
      }
      year = date.getFullYear();
      total = year + '-' + month + '-' + day;
      return total;
    }
  </script>
<% end %>

<% content_for :stylesheet do %>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css' rel='stylesheet' />
  <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.css' type='text/css' />
<% end %>